---
title: "R Notebook"
author: Tanzila
date: 1/7/2022
output: html_notebook
---

The [R plugin](https://www.jetbrains.com/help/pycharm/r-plugin-support.html) for IntelliJ-based IDEs provides
handy capabilities to work with the [R Markdown](https://www.jetbrains.com/help/pycharm/r-markdown.html) files.
To [add](https://www.jetbrains.com/help/pycharm/r-markdown.html#add-code-chunk) a new R chunk,
position the caret at any line or the code chunk, then click "+".

## Loading required package: ranger
```{r}
require(ranger)
```
## Loading required package: here
```{r}
require(here)
```
# read phenotypic data
```{r}
pheno <- read.csv(here("HDRA/HDRA_Data/HDRA_Raw", "HDRA_pheno_sel.csv"), row.names = 1)
```


#check the size of selected data
```{r}
dim(pheno)
```
#generate cv.ids (use them for all 18 traits)
```{r}
n.fold <- 10
n.rep <- 5
n.sample <- nrow(pheno)
cv.id <- matrix(NA, nrow = n.sample, ncol = n.rep)
for(i in 1:n.rep) {
  cv.id[,i] <- sample(1:n.sample %% n.fold) + 1
}
rownames(cv.id) <- rownames(pheno)
colnames(cv.id) <- paste0("CV", 1:n.rep)
print(n.sample)
print(cv.id)
```